---
#kaszlikowski.s@gmail.com
#

- name:               Dodanie VLAN POOL /
  hosts:              apics
  connection:         local
  gather_facts:       no

  vars_prompt:

  - name: "apic_username"
    prompt: "Wprowadz uzytkownika"
    private: no
  - name: "apic_userpass"
    prompt: "Wprowadz haslo"
    private: yes


  vars:
    apic_info:        &apic_info
      hostname: '{{ hostvars[inventory_hostname].apic_ip }}'
      # username: '{{ apic_username }}'
      # password: '{{ apic_userpass }}'
      username: 'pod1'
      password: 'Admin1sisko$'
      validate_certs: no
      use_proxy: no

    vlan_pools:
      vlanPoolName: POD1_SK

    phys_dom:
        physDomName: POD1_SK_PHY

    aep: POD1_SK-AEP

  tasks:
  # Create a snapshot
  # DOCS: https://docs.ansible.com/ansible/2.7/modules/aci_config_snapshot_module.html#aci-config-snapshot-module
  - name: Create snapshot
    aci_config_snapshot:
      <<: *apic_info
      state: present
      export_policy: config_backup
      max_count: 10
      description: snapshot (ansible)
    delegate_to: localhost

  # Create Vlan pool
  - name: Add a new {{vlan_pools.vlanPoolName}} VLAN pool
    aci_vlan_pool:
      <<: *apic_info
      pool: "{{vlan_pools.vlanPoolName}}"
      pool_allocation_mode: static
      description: POD1 SK VLANs
      state: present
    delegate_to: localhost

  # Add vlan block to vlan pool
  - name: Add to VLAN Pools {{vlan_pools.vlanPoolName}}
    aci_rest:
      <<: *apic_info
      use_proxy:      no
      path:           /api/mo/.json
      method:         post
      content:
        fvnsVlanInstP:
          attributes:
            allocMode: static
            annotation: ''
            descr: ''
            dn: uni/infra/vlanns-[{{vlan_pools.vlanPoolName}}]-static
            name: "{{vlan_pools.vlanPoolName}}"
            nameAlias: ''
            ownerKey: ''
            ownerTag: ''
            status: modified
          children:
          - fvnsEncapBlk:
              attributes:
                allocMode: static
                annotation: ''
                descr: ""
                from: 'vlan-1100'
                name: ''
                nameAlias: ''
                role: external
                to: 'vlan-1109'

  # Add vlan block to vlan pool
  - name: Add a new 1110 - 1119 VLAN encap block to {{vlan_pools.vlanPoolName}} VLAN pool
    aci_rest:
      <<: *apic_info
      use_proxy:      no
      path:           /api/mo/.json
      method:         post
      content:
        fvnsVlanInstP:
          attributes:
            allocMode: static
            annotation: ''
            descr: ''
            dn: uni/infra/vlanns-[{{vlan_pools.vlanPoolName}}]-static
            name: "{{vlan_pools.vlanPoolName}}"
            nameAlias: ''
            ownerKey: ''
            ownerTag: ''
            status: modified
          children:
          - fvnsEncapBlk:
              attributes:
                allocMode: inherit
                annotation: ''
                descr: ""
                from: 'vlan-1110'
                name: ''
                nameAlias: ''
                role: external
                to: 'vlan-1119'

  # Add a new AEP
  - name: Add a new AEP
    aci_aep:
      <<: *apic_info
      aep: '{{ aep }}'
      description: default
      state: present
    delegate_to: localhost

  # Add a new physical domain
  - name: Add a new {{phys_dom.physDomName}} physical domain
    aci_domain:
      <<: *apic_info
      domain: "{{ phys_dom.physDomName }}"
      domain_type: phys
      state: present

  # Add AEP to domain binding
  - name: Add AEP to domain binding
    aci_aep_to_domain: &binding_present
      <<: *apic_info
      aep: '{{ aep }}'
      domain: "{{ phys_dom.physDomName }}"
      domain_type: phys
      state: present
    delegate_to: localhost

  # Bind a new physical domain to VlanPool
  - name: Bind a {{phys_dom.physDomName}} physical domain to {{vlan_pools.vlanPoolName}} VLAN pool
    aci_domain_to_vlan_pool:
      <<: *apic_info
      domain: "{{phys_dom.physDomName}}"
      domain_type: phys
      pool: '{{vlan_pools.vlanPoolName}}'
      pool_allocation_mode: static
      state: present
    delegate_to: localhost

  # Interface Policy Groups -> Leaf Access Port
  # https://docs.ansible.com/ansible/latest/modules/aci_interface_policy_leaf_policy_group_module.html#aci-interface-policy-leaf-policy-group-module
  - name: Create a Leaf Access Port Policy Group
    aci_interface_policy_leaf_policy_group:
      <<: *apic_info
      lag_type: leaf
      policy_group: 'POD1_SK_eth1-1'
      description: POD1_SK_eth1/1 description
      lldp_policy: POD1_LLDP_On
      cdp_policy: POD1_CDP_ON
      aep: '{{ aep }}'
      # link_level_policy: whateverlinklevelpolicy
      state: present
    delegate_to: localhost

  # Interface Policy Groups -> VPC
  - name: Create a Virtual Port Channel (VPC) Interface Policy Group
    aci_interface_policy_leaf_policy_group:
      <<: *apic_info
      lag_type: node
      policy_group: 'POD1_SK_VPC-CH1'
      link_level_policy: '10G'
      description: POD1_SK_VPC-CH1 description
      lldp_policy: POD1_LLDP_On
      cdp_policy: POD1_CDP_ON
      port_channel_policy: POD1_SK_PortChannel_no_suspend
      aep: '{{ aep }}'
      state: present
    delegate_to: localhost
